
   - name: install nginx server
     ansible.builtin.dnf:
       name: nginx
       state: latest

   - name: starat and enable nginx
     ansible.builtin.service:
       name: nginx
       state: started
       enabled: yes

   - name: run pre req
     ansible.builtin.import_role:
       name: common
       tasks_from: app-pre-req  
      

   - name: copy backend conf
     ansible.builtin.template:
       src: expense.conf
       dest: /etc/nginx/default.d/expense.conf
     notify:
       - restart nginx 
         # - name: restart nginx
     #  ansible.builtin.service:
       # name: nginx
         #       state: started     

